### ISSUE TITLE
Projects that support arabic text rendering/shaping

### ISSUE THREAD

**Issue by abom** [01walid/awesome-arabic#18]
The first thing i expected to see here, also some notable font projects for example?

https://github.com/HOST-Oman/libraqm
https://github.com/harfbuzz/harfbuzz

https://github.com/alif-type/amiri

**Comment by 01walid** [comment]
Thank you, do you mind opening a PR ? or do you want me to add them myself ?

**Comment by abom** [comment]
Will create a PR.
