### ISSUE TITLE
Where can I add Wudooh?

### ISSUE THREAD

**Issue by basshelal** [01walid/awesome-arabic#22]
Hi there,

[Wudooh](https://github.com/basshelal/Wudooh) is a Chrome and Firefox extension that makes Arabic script clearer

Not sure if this even fits in here but if it does, which section would it go under?

Many thanks :)

**Comment by 01walid** [comment]
Hi, 
Nice work on wudooh, it definitely fits in here :)

I'd include it under Miscellaneous or preferably create a new "Browser extensions" section.

Feel free to send me a pull request.

**Comment by basshelal** [comment]
Done #23
