### ISSUE TITLE
1.5 billion words Arabic Corpus

### ISSUE THREAD

**Issue by linuxscout** [01walid/awesome-arabic#36]
http://www.abuelkhair.net/index.php/en/arabic/abu-el-khair-corpus
Abu El-khair, I. (2016). 1.5 billion words Arabic Corpus. ArXiv e-prints, 1611.04033(November, 2016) , Available at: https://128.84.21.199/abs/1611.04033

**Comment by 01walid** [comment]
@linuxscout 
sorry I somehow missed the notification for this issue, I'll add the links to this repo.
